### ISSUE TITLE
JRaw value is given twice when serializing

### ISSUE THREAD

**Issue by jorik90** [JamesNK/Newtonsoft.Json.Glimpse#1]
If I have Newtonsoft.Json.Glimpse installed, the serializing of an JRaw value will give the output twice.

For example the following code:

```
var settings = new Newtonsoft.Json.Linq.JRaw("$('#element')");
string configuration = Newtonsoft.Json.JsonConvert.SerializeObject(settings);
```

It should return

```
$('#element')
```

but it returns the following instead:

```
$('#element')$('#element')
```

I can reproduce it when I create a new ASP.NET Web Application using the ASP.NET 4.5.2 MVC template. Then I update the Newtonsoft.Json package to the latest version (7.0.1), install Glimpse, Glimpse.Mvc5 and Newtonsoft.Json.Glimpse. When I remove the Newtonsoft.Json.Glimpse package, I get the expected result again.

**Comment by JamesNK** [comment]
This is a bug in Json.NET. It will be fixed in the next release.
